### ISSUE TITLE
Error System.Security.Permissions

### ISSUE THREAD

**Issue by eduardoed5** [feinoujc/Mandrill.net#55]
when executing sending messages send me the following error? What can be the cause?

The type initializer for 'Mandrill.SystemWebMandrillRequest' threw an exception.-Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

**Comment by feinoujc** [comment]
@eduardoed5 
I think you're running into some partial trust issues see here http://forums.asp.net/t/1422162.aspx

The issue is because of this code [here](https://github.com/feinoujc/Mandrill.net/blob/fcc3e0eb545b4f91225527fbb045836e9bbea095/src/Mandrill.net/MandrillRequest.cs#L36)
the issue explained in detail here
http://haacked.com/archive/2010/11/04/assembly-location-and-medium-trust.aspx/
